server:
  port: 8282
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/school
    username: postgres
    password: password
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          initial-interval: 3s
          enabled: true
          max-attempts: 5
          max-interval: 5s
          multiplier: 1
        missing-queues-fatal: false

feign:
  client:
    url: http://localhost:8181

redis:
  server:
    urls: redis://localhost:6379

jwt:
  accessToken:
    expiration:
      time: 15
  refreshToken:
    expiration:
      count: 50
      time: 21600

rabbitmq:
  queue:
    test: TEST_Q
    test-dlq: TEST_DLQ
